name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker Image from frontend folder
      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest ./frontend

      # Push Image
      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop frontend-app || true
            docker rm frontend-app || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest
            docker run -d \
              --name frontend-app \
              -p 80:80 \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest